Created election-factory test script
mowblox/auditable-blockchain-voting-system pull request #28
Opened 2024-08-30 07:38 UTC by Ratawine7

2024-08-30 07:44 UTC, Ratawine7 commented
I raised PR

2024-08-30 17:28 UTC, mikehammond requested changes

2024-08-30 17:28 UTC, mikehammond commented on blockchain/pnpm-lock.yaml
@Ratawine7 Because we do not want to exchange lock files you have to delete this file and then add it to the .gitignore file so that it stays only with you.

2024-08-30 17:28 UTC, mikehammond commented on blockchain/package.json
> +    "@nomicfoundation/hardhat-network-helpers": "^1.0.11",
@Ratawine7 This is a peer dependency of **@nomicfoundation/hardhat-toolbox** so you do not have to install it alone.

2024-08-30 17:28 UTC, mikehammond commented on blockchain/package.json
> +    "ethers": "^6.13.2"
@Ratawine7 **ethers** is also a peer dependency of **@nomicfoundation/hardhat-toolbox** so no need to install it.

2024-08-30 20:47 UTC, closed without merging

2024-08-30 20:55 UTC, Ratawine7 commented
1. The getOwner() function in the test file is a function defined in the ElectionFactory smart contract. This function is used to return the address of the contract's owner. That's why it's found in the test file.

2. removed the peer dependencies
3. raised PR

2024-08-30 21:26 UTC, mikehammond commented on blockchain/pnpm-lock.yaml
@Ratawine7 Still left with this one.

2024-08-31 07:28 UTC, Ratawine7 commented
removed
I am not feeling well which is why it is delayed.